name: "Install demp"
description: "A GitHub Action to install a specific version of the demp Go CLI from https://github.com/rianfowler/demp."

inputs:
  version:
    description: "Version of demp to install (e.g., 1.0.0)"
    required: true
    default: "1.0.0"

runs:
  using: "composite"
  steps:
    - name: Run install script
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        KEY: "092017BA1C395379" # Hardcoded public key ID
      run: |
        chmod +x "${{ github.action_path }}/install-demp.sh"
        "${{ github.action_path }}/install-demp.sh" ${VERSION} ${KEY}
