#!/usr/bin/env bash
set -euo pipefail

# First argument: version (e.g., "0.1.13")
VERSION="${1}"
# Second argument: Public key ID or fingerprint used to sign the checksum file.
KEY_ID="${2}"

OS=$(uname | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
if [[ "${ARCH}" == "x86_64" ]]; then
  ARCH="amd64"
fi

BASE_URL="https://github.com/rianfowler/demp/releases/download/v${VERSION}"
BINARY_NAME="demp_${VERSION}_${OS}_${ARCH}.tar.gz"
CHECKSUM_NAME="demp_${VERSION}_checksums.txt"
SIGNATURE_NAME="${CHECKSUM_NAME}.sig"  # This is the signature file generated by GoReleaser

echo "Downloading binary from ${BASE_URL}/${BINARY_NAME}"
curl -sSL -o "${BINARY_NAME}" "${BASE_URL}/${BINARY_NAME}"

echo "Downloading checksum from ${BASE_URL}/${CHECKSUM_NAME}"
curl -sSL -o "${CHECKSUM_NAME}" "${BASE_URL}/${CHECKSUM_NAME}"

echo "Downloading signature for checksum from ${BASE_URL}/${SIGNATURE_NAME}"
curl -sSL -o "${SIGNATURE_NAME}" "${BASE_URL}/${SIGNATURE_NAME}"

echo "Verifying GPG signature for checksum file..."

# Check if the public key is already in the keyring; if not, fetch it from a keyserver.
if ! gpg --list-keys "${KEY_ID}" > /dev/null 2>&1; then
  echo "Public key ${KEY_ID} not found locally; fetching from keyserver..."
  gpg --keyserver keys.openpgp.org --recv-keys "${KEY_ID}"
fi

# Verify the signature.
gpg --batch --no-tty --verify "${SIGNATURE_NAME}" "${CHECKSUM_NAME}" || {
  echo "ERROR: GPG signature verification failed for ${CHECKSUM_NAME}."
  exit 1
}
echo "GPG signature verification passed."

echo "Verifying checksum..."

# Debug: Print the content of the checksum file.
echo "Checksum file contents:"
cat "${CHECKSUM_NAME}"

EXPECTED_CHECKSUM=$(grep "${BINARY_NAME}" "${CHECKSUM_NAME}" | awk '{print $1}')
if [ -z "$EXPECTED_CHECKSUM" ]; then
  echo "ERROR: Checksum for ${BINARY_NAME} not found in ${CHECKSUM_NAME}."
  exit 1
fi

ACTUAL_CHECKSUM=$(sha256sum "${BINARY_NAME}" | awk '{print $1}')

echo "Expected checksum: ${EXPECTED_CHECKSUM}"
echo "Actual checksum:   ${ACTUAL_CHECKSUM}"

if [ "${EXPECTED_CHECKSUM}" != "${ACTUAL_CHECKSUM}" ]; then
  echo "ERROR: Checksum verification failed. Expected ${EXPECTED_CHECKSUM} but got ${ACTUAL_CHECKSUM}."
  exit 1
fi

echo "Checksum verification passed."

echo "Extracting binary..."
tar -xzf "${BINARY_NAME}"

# Assuming the tarball extracts a binary named "demp"
chmod +x demp
sudo mv demp /usr/local/bin/demp

echo "demp ${VERSION} installed successfully!"
